blog/urls.py
from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    url(r'', include('tlanblog.urls')),
    # url(r'^admin/', admin.site.urls),
]

tlanblog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 17/6/19 下午12:52
# @Author  : Aries
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url,include
from django.conf.urls.static import static

from . import views
from django.contrib import admin
from blog import settings
from blog.upload import upload_img

urlpatterns = [
    url(r'^$', views.index),
    url(r'^assort/$', views.assort),
    url(r'^sliders/(\d{1,6})/(?P<article_id>(\d{1,10}))/$', views.article_context),
    url(r'^article/(\d{1,6})/(?P<article_id>(\d{1,10}))/$', views.article_context),
    url(r'^ajax/arts/$', views.ajax_articles),
    url(r'^comment/add/$',views.comment_add),
    url(r'^comment/del/$',views.comment_del),
    url(r'^comment/like/$',views.comment_like),
    url(r'^ckeditorUpload$',upload_img),
    url(r'^about/$', views.about),
    url(r'^login/$',views.login_interface),
    url(r'^manager/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tlanblog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
# Create your models here.
#用户模型
class User(AbstractUser):
    alias = models.CharField(max_length=8,default="匿名",verbose_name="昵称")
    avatar = models.ImageField(upload_to="avatar/%Y/%m/%d",default="avatar/default.png",max_length=200,verbose_name="头像")
    qq = models.CharField(max_length=15,blank=True,null=True,verbose_name="QQ号码")
    mobile = models.CharField(max_length=11,blank=True,null=True,unique=True,verbose_name="手机号码")

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = "用户管理"
        ordering = ['-id']

    def __str__(self):
        return self.username

# 标签模型
class Tag(models.Model):
    name = models.CharField(max_length=6, verbose_name="标签名")
    index = models.IntegerField(default=999, verbose_name="标签排序")
    tag_add_date = models.DateTimeField(auto_now=True,verbose_name="添加时间")
    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签管理"

    def __unicode__(self):
        return self.name

# 分类模型
class Category(models.Model):
    name = models.CharField(max_length=6, verbose_name="分类名称")
    index = models.IntegerField(default=999, verbose_name="分类排序")
    c_add_date = models.DateTimeField(auto_now_add=True,verbose_name="添加时间")
    class Meta:
        verbose_name = "分类"
        verbose_name_plural = "分类管理"
        ordering = ['-c_add_date']

    def __unicode__(self):
        return self.name

#文章模型
class Article(models.Model):
    title = models.CharField(verbose_name="文章标题",max_length=50)
    head_img = models.ImageField(upload_to="article/uploads/images/%Y/%m",default="article/default.png",verbose_name="文章头图")
    desc = models.CharField(verbose_name="文章描述",max_length=200)
    content = models.TextField(verbose_name="文章内容")
    click_count = models.IntegerField(default=0,verbose_name="点击次数")
    is_recommend = models.BooleanField(default=False, verbose_name="是否推荐")
    pub_date = models.DateTimeField(default=timezone.now,verbose_name="发布时间")
    user = models.ForeignKey(User, verbose_name="发布者")
    category = models.ForeignKey(Category,blank=True,null=True,verbose_name="文章分类")
    tag = models.ManyToManyField(Tag,verbose_name="标签")

    class Meta:
        verbose_name = "文章"
        verbose_name_plural="文章管理"
        ordering = ['-pub_date']

    def __unicode__(self):
        return self.title

# 评论模型
class Comment(models.Model):
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    content = models.TextField(max_length=500, verbose_name="评论内容")
    username = models.CharField(default='匿名',max_length=20, verbose_name="评论者")
    article = models.ForeignKey(Article, blank=True, null=True, verbose_name="文章")
    pid = models.ForeignKey('self', blank=True, null=True, verbose_name="父级评论")
    user_ip = models.GenericIPAddressField(default="0.0.0.0",verbose_name="用户IP")
    like = models.IntegerField(default=0,verbose_name="点赞数")
    atName = models.CharField(default="", max_length=20,verbose_name="@对象")
    class Meta:
        verbose_name = "评论"
        verbose_name_plural = "评论管理"
        ordering = ['-pub_date']

    def __unicode__(self):
        return str(self.id)

#大图文章
class SliderArticle(Article):
    index = models.IntegerField(verbose_name="大图排序")

    class Meta:
        verbose_name = "大图文章"
        verbose_name_plural = "大图文章"
        ordering = ['-pub_date']

    def __unicode__(self):
        return self.title

#站点信息管理
class SiteManage(models.Model):
    main_title = models.CharField(max_length=20,verbose_name="网站标题")
    change_date = models.DateTimeField(default=timezone.now, verbose_name="修改时间")
    about_title = models.CharField(max_length=30, default="关于博主",verbose_name="关于博主标题")
    about_info = models.TextField(max_length=1000, default="博主信息",verbose_name="关于内容")
    class Meta:
        verbose_name = "网页"
        verbose_name_plural = "网页管理"
        ordering = ['-change_date']
    def __unicode__(self):
        return self.main_title

tlanblog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.template.loader import get_template
#from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
from .models import *
from django.db.models import Q
from tlanblog.form import CommentForm
import json
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

def login_interface(request):
    return render(request,'user.html')
# 主页
def index(request):
     slider_as = SliderArticle.objects.all()[:4]
     context = base_data_proc(request,{'slider_as': slider_as})
     return render(request, 'index.html', context=context)

#搜索页
def assort(request):
    context = base_data_proc(request)
    return render(request,'search.html',context)

#关于
def about(request):
    about = SiteManage.objects.get(id = 1)
    context = base_data_proc(request, {'about':about})
    return render(request,'about.html', context)

#图片轮转
def slider_context(request, slider_id):
    article = SliderArticle.objects.get(id = slider_id)
    article.click_count+=1
    article.save()
    context = base_data_proc(request, {'article': article})
    return render(request, 'article.html',context)

def comment_add(request):
    if request.is_ajax() and request.method == 'POST':
        #print request.POST
        pid_str = request.POST['pid']
        pid = None
        if pid_str != "" and pid_str != None:
            try:
                pid_id = int(pid_str)
                pid = Comment.objects.get(id=pid_id)
            except Exception, e:
                print e.message
                pid = None
        else:
            pid = None
        oHfName = request.POST['oHfName']
        content = request.POST['content']
        article_id = int(request.POST['article'])
        article = Article.objects.get(id = article_id)
        user_ip = request.META['REMOTE_ADDR']
        if content != None or content != "":
            comment = Comment.objects.create(pid=pid, article=article, content=content, pub_date=timezone.now(), user_ip=user_ip, atName=oHfName)
            username = "游客 ***."+user_ip.split('.')[1] + ".***."+ user_ip.split('.')[-1]
            comment.username = username
            comment.save()
            #print username
            comment_json = {}
            comment_json['hfName'] = comment.username
            comment_json['hfTime'] = comment.pub_date.strftime("%Y-%m-%d %H:%M:%S")
            comment_json['atName'] = comment.atName
            comment_json['like'] = comment.like
            comment_json['id'] = comment.id
            #print comment_json['id']
            return HttpResponse(json.dumps(comment_json), content_type='application/json')
    raise Http404

def comment_like(request):
    if request.is_ajax() and request.method=='POST':
        comment_id = request.POST['comment_id']
        likes_num = request.POST['like']
        if comment_id.strip!="" and int(comment_id.strip()) and int(likes_num):
            id = int(comment_id)
            comment = Comment.objects.get(id=id)
            if comment!= None:
                comment.like = int(likes_num)
                comment.save()
                json_like = {'like':comment.like}
                return HttpResponse(json.dumps(json_like),content_type='application/json')
    return Http404

def comment_del(request):
    if request.is_ajax() and request.method=='POST':
        comment_id = request.POST['comment_id']
        req_ip = request.META['REMOTE_ADDR']
        if comment_id.strip() != "" and int(comment_id.strip()):
            id = int(comment_id.strip())
            comment = Comment.objects.get(id=id)
            if(comment!=None and req_ip==comment.user_ip):
                comment.delete()
                is_ok = '1'
                json_ok = {'is_ok':is_ok}
                return HttpResponse(json.dumps(json_ok),content_type='application/json')
    return Http404

#文章内容
def article_context(request, article_id):
    comment_form = CommentForm
    all_arts = Article.objects.all()
    total_num = all_arts.count()
    article = all_arts.get(id = article_id)
    comments = Comment.objects.filter(article= article).order_by('id')
    article_id = int(article_id)
    article_pre_id = article_id-1
    article_next_id = article_id+1
    article_pre = None
    article_next = None
    if article_pre_id > 0 and article_pre_id<=total_num:
        article_pre = all_arts.get(id = article_pre_id)
    if article_next_id >0 and article_next_id<=total_num:
        article_next = all_arts.get(id = article_next_id)
    article.click_count+=1
    article.save()
    #评论帅选
    comment_list = []
    for comment in comments:
        for item in comment_list:
            if not hasattr(item, 'child_comment'):
                setattr(item, 'child_comment', [])
            if comment.pid == item:
                item.child_comment.append(comment)
        if comment.pid is None:
            comment_list.append(comment)

    context = base_data_proc(request,{'comment_form':comment_form,'comments': comment_list,'article': article,'article_pre': article_pre, 'article_next': article_next})
    return render(request, 'article.html',context)

#日期分组函数
def date_groups_get():
    date_groups = Article.objects.raw(
        'SELECT id, pub_date as pub_time, COUNT(*) as count FROM tlanblog_article GROUP BY strftime("%Y-%m", pub_date) ORDER BY pub_date DESC'
    )
    return date_groups


#基础数据返回
def base_data_proc(request, context_dict={}):
    site_title = SiteManage.objects.get(id=1).main_title
    tags = Tag.objects.all()
    categorys = Category.objects.all().filter()
    articles_rec = Article.objects.all().filter(is_recommend=True)[:5]
    date_category = date_groups_get()
    context = {
        'site_title': site_title,
        'tags': tags,
        'categorys': categorys,
        'articles_rec': articles_rec,
        'date_category': date_category,
        'ip_address': request.META['REMOTE_ADDR'],
    }
    context.update(context_dict)
    return context

def ajax_articles(request):
    if request.is_ajax() and request.GET:
        type = request.GET.get('type')
        keywords = request.GET.get('keywords')
        articles = None
        if type=="index":
            articles = Article.objects.all()
        elif type=="category":
            articles = Article.objects.all().filter(category__name=keywords)
        elif type=="datetime":
            date_s = keywords.split('-')
            try:
                if len(date_s) == 2 and int(date_s[0] and int(date_s[1])):
                    articles = Article.objects.all().filter(pub_date__year=date_s[0]).filter(pub_date__month=date_s[1])
                else:articles = None
            except Exception,e:
                print '异常：'+e.message
                articles = None
        elif type=="tag":
            articles = Article.objects.all().filter(tag__name=keywords)
        elif type=="search":
            articles = Article.objects.all().filter(
                Q(title__contains=keywords) |
                Q(desc__contains=keywords) |
                Q(content__contains=keywords) |
                Q(category__name__contains=keywords) |
                Q(tag__name__contains=keywords)
            ).distinct()

        else:
            print '数据类型错误，查询失败！'
            raise Http404
        jsonstr = convert_to_jsontype(type, articles)
        return HttpResponse(jsonstr, content_type='application/json')
    else:
        raise Http404

#将文章基本信息转化为json返回字符串
def convert_to_jsontype(type, articles):
    result = {}
    result['type'] = type
    result['status'] = "ok"
    result['count'] = len(articles)
    art_list = []
    for art in articles:
        art_json = {}
        art_json['url'] = "/article/%s/%s/" %(art.pub_date.strftime("%Y%m"),art.id)
        art_json['title'] = art.title
        art_json['user'] = art.user.alias
        art_json['head_img'] = art.head_img.url
        art_json['pub_date'] = art.pub_date.strftime("%Y-%m-%d %H:%M")
        art_json['desc'] = art.desc
        art_json['category'] = art.category.name
        art_json['comments_count'] = art.comment_set.count()
        art_json['click_count'] = art.click_count
        art_list.append(art_json)

    result['articles'] = art_list
    return json.dumps(result)

tlanblog/templates/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#	<head>#}
{#		<meta charset="utf-8">#}
{#		<meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#		<meta name="viewport" content="width=device-width, initial-scale=1">#}
{#		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->#}
{#		<meta name="description" content="">#}
{#		<meta name="author" content="">#}
{#		<link rel="icon" href="favicon.ico">#}
{#		<title>About me!</title>#}
{#		<!-- Bootstrap core CSS -->#}
{#		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">#}
{#		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">#}
{#		<!-- Custom styles for this template -->#}
{#		<link href="{% static 'css/jquery.bxslider.css' %}" rel="stylesheet">#}
{#		<link href="{% static 'css/style.css' %}" rel="stylesheet">#}
{#        <style type="text/css">#}
{#            h2{#}
{#                font-size: 18px;#}
{#            }#}
{#        </style>#}
{#	</head>#}
{#	<body>#}
{#		<!-- Navigation -->#}
{#		<nav class="navbar navbar-inverse navbar-fixed-top">#}
{#			<div class="container">#}
{#                {% include "header.html" %}#}
{#				</div>#}
{#				<!--/.nav-collapse -->#}
{#			</div>#}
{#		</nav>#}
{##}
{#		<div class="container">#}
{#		<header>#}
{#			<a href="/"><img src="{% static 'images/logo.png' %}"></a>#}
{#		</header>#}
        {% block art_content %}
            <section>
                <div class="row">
                    <div class="col-md-12">
                        <article class="blog-about">
                            <div class="blog-about-body">
                                <h2>{{ about.about_title }}</h2>
                                <div class="blog-about-text">
                                    {{ about.about_info }}
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
		    </section>
        {% endblock %}

{#		</div><!-- /.container -->#}
{##}
{#		<footer class="footer">#}
{#			<div class="footer-bottom">#}
{#				{% include "footer.html" %}#}
{#			</div>#}
{#		</footer>#}
{##}
{#		<!-- Bootstrap core JavaScript#}
{#			================================================== -->#}
{#		<!-- Placed at the end of the document so the pages load faster -->#}
{#	</body>#}
{#</html>#}

tlanblog/templates/article_list.html
<!-- article_list.html -->
{% load staticfiles %}
{% for article in articles %}
<article class="art-item">
    <div class="art_item_img">
        <a href="/article/{{ article.pub_date | date:'Ym' }}/{{ article.id }}/"><img src="{{ article.head_img.url }}" alt=""></a>
    </div>
    <div class="art_item_info">
        <dl>
            <dd>
                <h2><a href="/article/{{ article.pub_date | date:'Ym' }}/{{ article.id }}/">
{{ article.title }} </a>
                </h2>
            </dd>
            <dd class="art_item_desc">
                <p>
                    {{ article.desc }}
                </p>
            </dd>
        </dl>
    </div>
    <div class="art_item_meta"><span style="float: left;text-align: center;display: block;padding-left: 5px;font-weight: 400;padding-right: 5px;background-color: #c7ddef"><a>{{ article.category}}</a></span><i class="fa fa-user-circle-o"></i><a href="/about">{{ article.user.alias }}</a><span></span><i class="fa fa-clock-o"></i>{{ article.pub_date }}<span></span><span><i class="fa fa-eye"></i>{{ article.click_count }}</span><span></span><i class="fa fa-comment-o"></i><a href="/article/{{ article.pub_date | date:'Ym' }}/{{ article.id }}/">{{ article.comment_set.count }}</a></span>
    </div>
</article>
{% endfor %}


{#<div class="pagelist">#}
{#    <em>共{{ articles.paginator.num_pages }}页</em>#}
{#    <a href="?page=1">首页</a>#}
{#    {% if articles.has_previous %}#}
{#        <a href="?page={{ articles.previous_page_number }}">上一页</a>#}
{#        {% else %}#}
{#        <em>上一页</em>#}
{#    {% endif %}#}
{#    {% for page in articles.paginator.page_range %}#}
{#        {% if articles.number == page %}#}
{#            <em>{{ articles.number }}</em>#}
{#            {% else %}#}
{#            <a href="?page={{page }}">{{page }}</a>#}
{#        {% endif %}#}
{#    {% endfor %}#}
{##}
{#    {% if articles.has_next %}#}
{#    <a href="?page={{ articles.next_page_number }}">下一页</a>#}
{#        {% else %}#}
{#        <em>下一页</em>#}
{#    {% endif %}#}
{#    {% if articles.end_index|add:'-1' == 1 %}#}
{#        <em>尾页</em>#}
{#        {% else %}#}
{#        <a href="?page={{ articles.end_index|add:'-1'}}">尾页</a>#}
{#    {% endif %}#}
{#</div>#}

tlanblog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="edge">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name=”renderer” content=”webkit|ie-comp|ie-stand”>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="">
		<meta name="author" content="">
        <link rel="icon" href="favicon.ico">
		<title>{% block title %}{% endblock %}</title>
		<!-- Bootstrap core CSS -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<!-- Custom styles for this template -->
		<link href="{% static 'css/jquery.bxslider.css' %}" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/page.css' %}" rel="stylesheet">
        {% block comstom_css %}{% endblock %}
	</head>
	<body>
		<!-- Navigation -->
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
                {% include "header.html" %}
				<!--/.nav-collapse -->
			</div>
		</nav>

		<div class="container" style="margin-top: 56px">
{#            <header>#}
{#			    <a href="index.html"><img src="{% static 'images/logo.png' %}"></a>#}
{#		    </header>#}
            <section class="main-slider">
                {% block nav_slider %}{% endblock %}
	        </section>
            <section>
                <div>
                    <div class="row">
                        <div class="col-md-8">
                        {% block art_content %}
                        {% endblock %}
                        </div>
                        <div class="col-md-4 sidebar-gutter">
                            {% include "right_side.html" %}
                        </div>
                    </div>
                </div>
            </section>
		</div><!-- /.container -->

		<footer class="footer">
			<div class="footer-bottom">
				{% include "footer.html" %}
			</div>
		</footer>
		<!-- Bootstrap core JavaScript
			================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/jquery.min.map' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/jquery.bxslider.js' %}"></script>
		<script src="{% static 'js/mooz.scripts.min.js' %}"></script>
{#        <script src="http://www.jq22.com/jquery/jquery-1.10.2.js"></script>#}
        <script src="{% static 'js/page.js' %}"></script>
        <script src="{% static 'js/getArticles.js' %}"></script>
        <script src="{% static 'js/tags.js' %}"></script>

        {% block comstom_js %}{% endblock %}
	</body>
</html>

tlanblog/templates/footer.html
<!-- footer.html -->
<i class="fa fa-copyright"></i> Copyright 2017. All rights reserved.<br>友情链接：<a href="http://www.w3school.com.cn/" target="_blank" title="模板之家">W3School</a>

tlanblog/templates/header.html
<!-- header.html -->
<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
</div>
<div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li class="active"><a href="/">博客主页</a></li>
        <li><a href="/learn">学习推荐</a></li>
        <li><a href="/projects">项目案例</a></li>
        <li><a href="/books">电子书城</a></li>
        <li><a href="/about">关于博主</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
        <li><a href="#"><i class="fa fa-reddit"></i></a></li>
    </ul>
</div>

tlanblog/templates/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% block title %}Welcome | Tlan's Blog{% endblock %}
{% block nav_slider %}
    {% include 'slider_bar.html' %}
{% endblock %}
{% block art_content %}
<div class="searchInfo"></div>
<div class="art_list"></div>
<div class="page">
    <ul class="pageMenu clearfix">
        <li class="firstPage">首页</li>
        <li class="prevPage"> < 上一页 </li>
        <div class="pageObj">
        </div>
        <li class="nextPage"> 下一页 > </li>
        <li class="lastPage" title="">尾页</li>
        <li class="jumpTo">跳转</li>
        <li class="last" style="height: 32px">
        <input type="number" class="keuInput" value="1"/>
        </li>
    </ul>
</div>
{% endblock %}
{% block comstom_js %}
    <script type="text/javascript">
    initArticlePage("index","");
    </script>
{% endblock %}


tlanblog/templates/right_side.html
<!-- rigt_side.html -->
{% load staticfiles %}

<aside>
    <div class="sidebar-widget-search">
        <h3 class="sidebar-title">博文搜索</h3>
        <div class="search-container">
              <input id="searchText" placeholder="搜索从这里开始..." type="text"/>
              <button class="search-button" type="submit"/>
        </div>
    </div>
    <!-- sidebar-widget -->
    <div class="sidebar-widget-other">
        <h3 class="sidebar-title">文章分类</h3>
        <div class="widget-container">
             <div class="categ_list">
            {% for category in categorys %}
                {% if category.article_set.count > 0 %}
                <li title="{{ category.name }}"><i class="fa fa-folder-o"></i><span class="left">{{ category.name }}</span><span class="right"><i class="fa fa-flag"></i>{{ category.article_set.count }}</span></li>
                {% endif %}
            {% endfor %}
             </div>
        </div>
    </div>

    <!-- sidebar-widget -->
    <div class="sidebar-widget-other">
        <h3 class="sidebar-title">日期分类</h3>
        <div class="widget-container">
            <div class="date_list">
            {% for t_category in date_category %}
               <li title="{{ t_category.pub_time | date:'Y-m' }}"><i class="fa fa-calendar-check-o"></i><span class="left">{{ t_category.pub_time | date:'Y年m月' }}</span><span class="right"><i class="fa fa-flag"></i>{{ t_category.count }}</span></li>
            {% endfor %}
            </div>
        </div>
    </div>
    <!-- sidebar-widget -->
    <div class="sidebar-widget-other" id = sidebar-tags>
        <h3 class="sidebar-title">标签检索</h3>
        <div class="widget-container" id = "tags">
            {% for tag in tags %}
                <label class="">{{ tag.name }}</label>
            {% endfor %}
        </div>
    </div>
    <!-- sidebar-widget -->
    <div class="sidebar-widget-other">
        <h3 class="sidebar-title">推荐阅读</h3>
        <div class="widget-container">
            {% for article in articles_rec %}
            <article class="art_item_good">
                <div class="art_item_good_img">
                    <a href="article.html"><img src="{{ article.head_img.url }}" alt=""></a>
                </div>
                <div class="art_item_good_info">
                    <h2><a href="/article/{{ article.pub_date | date:'Ym' }}/{{ article.id }}/">{{ article.title }}</a></h2>
                    <div class="art_item_good_meta">
                        <span style="float: left;text-align: center;display: block;padding-left: 5px;font-weight: 400;padding-right: 5px;background-color: #c7ddef"><a href="/about">{{ article.category}}</a></span><span><i class="fa fa-clock-o"></i>{{ article.pub_date | date:"Y-m-d" }}</span><span><i class="fa fa-eye"></i>{{ article.click_count }}</span><span><i class="fa fa-comment-o"></i><a href="/article/{{ article.pub_date | date:'Ym' }}/{{ article.id }}/">{{ article.comment_set.count }}</a></span>
                    </div>
                </div>
            </article>
            {% endfor %}
        </div>
    </div>
</aside>

tlanblog/templates/search.html
<!-- search.html -->
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Welcome | Tlan's Blog{% endblock %}

{% block art_content %}
<div class="searchInfo"></div>
<div class="art_list"></div>
<div class="page">
    <ul class="pageMenu clearfix">
        <li class="firstPage">首页</li>
        <li class="prevPage"> < 上一页 </li>
        <div class="pageObj">
        </div>
        <li class="nextPage"> 下一页 > </li>
        <li class="lastPage" title="">尾页</li>
        <li class="jumpTo">跳转</li>
        <li class="last" style="height: 32px">
        <input type="number" class="keuInput" value="1"/>
        </li>
    </ul>
</div>
{% endblock %}
{% block comstom_js %}
    <script type="text/javascript">
    window.onload = function () {
        var type=getUrlParam("type");
        var keywords = getUrlParam("keywords");
        initArticlePage(type, keywords);
        //alert(window.location.href);
    };
    </script>
{% endblock %}

tlanblog/templates/slider_bar.html
<!-- slider_bar.html -->
{% load staticfiles %}
<ul class="bxslider">
    {% for slider_a in slider_as %}
    <li><div class="slider-item"><a href="/sliders/{{ slider_a.pub_date | date:'Ym' }}/{{ slider_a.id }}/"><img src="{{ slider_a.head_img.url }}" title="{{ slider_a.title }}" /></a><h2><a href="/sliders/{{ slider_a.pub_date | date:'Ym' }}/{{ slider_a.id }}/" alt="{{ slider_a.title }}">{{ slider_a.title }}</a></h2></div></li>
    {% endfor %}
</ul>